server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081/api/products
          predicates:
            - Path=/api/products/**

        - id: inventory-service
          uri: http://localhost:8080/api/inventory
          predicates:
            - Path=/api/inventory/**

        - id: auth-service
          uri: http://localhost:8082/api/auth
          predicates:
            - Path=/api/auth/**

        - id: sale-service
          uri: http://localhost:8085/api/sales
          predicates:
            - Path=/api/sales/**

        - id: client-service
          uri: http://localhost:8083/api/clients
          predicates:
            - Path=/api/clients/**

