server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product:8081/api/products
          predicates:
            - Path=/api/products/**

        - id: inventory-service
          uri: http://inventory:8080/api/inventory
          predicates:
            - Path=/api/inventory/**

        - id: auth-service
          uri: http://authentication:8082/api/auth
          predicates:
            - Path=/api/auth/**

        - id: sale-service
          uri: http://sales:8085/api/sales
          predicates:
            - Path=/api/sales/**

        - id: client-service
          uri: http://client:8083/api/clients
          predicates:
            - Path=/api/clients/**

