server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: producto-service
          uri: http://product:8081/api/producto
          predicates:
            - Path=/api/producto/**

        - id: movimiento-service
          uri: http://movement:8080/api/movimiento
          predicates:
            - Path=/api/movimiento/**

        - id: auth-service
          uri: http://authentication:8082/api/auth
          predicates:
            - Path=/api/auth/**

        - id: ventas-service
          uri: http://sales:8085/api/ventas
          predicates:
            - Path=/api/ventas/**

        - id: client-service
          uri: http://client:8083/api/clientes
          predicates:
            - Path=/api/clientes/**

